default_platform(:ios)

platform :ios do
  desc "Run unit tests for CDTests target"
  lane :fast_tests do
    scan(
      project: "CD.xcodeproj",
      scheme: "CD",
      devices: ["iPhone 15 Pro"],
      only_testing: ["CDTests"],
      clean: true,
      output_types: "html,junit",    
      output_directory: "fastlane/test_output"
    )
  end
end
