default_platform(:ios)

platform :ios do
  desc "Run unit tests for CDTests target"
  lane :fast_tests do
    scan(
      project: "CD.xcodeproj",
      scheme: "CD",
      only_testing: ["CDTests"],
      destination: "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0",
      clean: true,
      output_types: "html,junit",    
      output_directory: "fastlane/test_output"
    )
  end
end
