name: iOS CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Xcode environment
      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      # Step 3: Build and test the project
      - name: Build and Test
        run: |
          xcodebuild test \
            -project StructSetProject.xcodeproj \
            -scheme StructSetProject \
            -destination 'platform=iOS Simulator,name=iPhone 14'
