name: iOS CI Pipeline

on:
  pull_request:
    branches:
      - second
  push:
    branches:
      - second

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Ensure this matches your local Ruby version
          bundler-cache: true # Enable caching for Bundler dependencies

      # Step 3: Debug to verify Gemfile exists
      - name: Verify Gemfile exists
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in Directory:"
          ls -al

      # Step 4: Install dependencies via Bundler
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --gemfile=./CD/Gemfile # <-- SPECIFIED THE GEMFILE LOCATION HERE

      # Step 5: Run tests using Fastlane
      - name: Run Tests with Fastlane
        run: bundle exec fastlane fast_tests
